const state={view:"dashboard",symbol:"SPY",prices:[],running:true,theme:"dark",strategy:{win:0.55,avgWin:0.04,avgLoss:0.025},watch:["SPY","QQQ","NVDA","AAPL","BTC-USD"]};
const navItems=[
 ["OVERVIEW","⌂","dashboard","Dashboard"],
 ["MARKET","◈","markets","Markets"],
 ["QUANT","∿","quant","Quant Lab"],
 ["STRATEGIES","◫","strategies","Strategy Lab"],
 ["BACKTEST","↗","backtest","Backtesting"],
 ["RISK","◉","risk","Risk Engine"],
 ["PORTFOLIO","▦","portfolio","Portfolio"],
 ["ALERTS","◌","alerts","Signals & Alerts"],
 ["LEARN","?","learn","Learn Mode"]
];
const modules=[
 ["Statistical Arbitrage","⇄","Find mean-reverting relationships between assets using spread, z-score, correlation and cointegration."],
 ["Kelly Criterion","K","Calculate mathematically suggested position sizing from win rate and payoff."],
 ["Black-Scholes","B","Estimate option value and Greeks with configurable volatility, rate and time."],
 ["Monte Carlo","M","Stress-test a strategy or portfolio across thousands of possible future paths."],
 ["Engle-Granger","EG","Test whether two price series have a statistically useful long-run relationship."],
 ["Markov Regime Model","MR","Classify market regimes and estimate transition probabilities."],
 ["Sentiment Analyzer","S","Turn news sentiment into a measurable market factor."],
 ["Multi-Factor Model","MF","Rank assets using momentum, value, quality, volatility and other factors."],
 ["BAB","β","Model Betting Against Beta and compare low/high beta exposure."],
 ["Asymmetric Bets","↗","Search for setups where expected upside materially outweighs downside."],
 ["Correlation Heatmap","▤","Map diversification and hidden concentration across the watchlist."],
 ["Insider Tracker","I","Track insider activity and convert it into a confidence signal."]
];

function nav(){document.getElementById("nav").innerHTML=navItems.map((n,i)=>i===0||n[0]!==navItems[i-1][0]?`<div class="section">${n[0]}</div><button class="${state.view===n[2]?'active':''}" onclick="go('${n[2]}')"><b>${n[1]}</b>${n[3]}</button>`:`<button class="${state.view===n[2]?'active':''}" onclick="go('${n[2]}')"><b>${n[1]}</b>${n[3]}</button>`).join("")}
function go(v){state.view=v;render()}
function toast(s){const t=document.getElementById("toast");t.textContent=s;t.classList.add("show");setTimeout(()=>t.classList.remove("show"),2200)}
function money(x){return x<1?x.toFixed(3):x.toLocaleString("en-US",{minimumFractionDigits:2,maximumFractionDigits:2})}
function randn(){let u=0,v=0;while(!u)u=Math.random();while(!v)v=Math.random();return Math.sqrt(-2*Math.log(u))*Math.cos(2*Math.PI*v)}
function seedPrices(n=220,start=630){let p=start,a=[];for(let i=0;i<n;i++){p*=Math.exp((0.00035-0.5*0.018**2)+0.018*randn());a.push(p)}return a}
function livePrices(){if(!state.prices.length)state.prices=seedPrices();let last=state.prices.at(-1);let next=last*Math.exp(0.00015+0.0035*randn());state.prices.push(next);if(state.prices.length>260)state.prices.shift()}
function drawChart(id,data,color=1){const c=document.getElementById(id);if(!c)return;const dpr=devicePixelRatio||1,rect=c.getBoundingClientRect();c.width=rect.width*dpr;c.height=rect.height*dpr;const x=c.getContext("2d");x.scale(dpr,dpr);const w=rect.width,h=rect.height,p=10;let min=Math.min(...data),max=Math.max(...data),span=max-min||1;x.strokeStyle="#17263a";x.lineWidth=1;for(let i=1;i<5;i++){let y=p+(h-2*p)*i/5;x.beginPath();x.moveTo(0,y);x.lineTo(w,y);x.stroke()}x.beginPath();data.forEach((v,i)=>{let px=p+(w-2*p)*i/(data.length-1),py=h-p-(v-min)/span*(h-2*p);i?x.lineTo(px,py):x.moveTo(px,py)});x.strokeStyle="#3b82f6";x.lineWidth=2;x.stroke();x.lineTo(w-p,h-p);x.lineTo(p,h-p);x.closePath();let g=x.createLinearGradient(0,0,0,h);g.addColorStop(0,"rgba(59,130,246,.22)");g.addColorStop(1,"rgba(59,130,246,0)");x.fillStyle=g;x.fill()}
function dashboard(){let p=state.prices.at(-1)||630, day=(p/state.prices[0]-1)*100;return `
<div class="page-head"><div><div class="eyebrow">Quant terminal / ${new Date().toLocaleTimeString("pl-PL")}</div><h1>Market Intelligence</h1><div class="sub">One workspace for research, strategies, risk and execution decisions.</div></div><div class="actions"><button class="btn" onclick="go('strategies')">＋ New strategy</button><button class="btn primary" onclick="go('quant')">Run quant scan</button></div></div>
<div class="grid stats">
${stat("Portfolio","$124,860","+2.84%","30D",1)}${stat("SPY",money(p),day.toFixed(2)+"%","simulated live",day>=0)}${stat("Risk score","32 / 100","Moderate","portfolio",null)}${stat("Sharpe","1.74","+0.31","vs benchmark",1)}${stat("Regime","Risk-on","68% confidence","Markov",1)}
</div>
<div class="grid dashboard-grid">
<div class="card chart-card"><div class="card-title"><b>${state.symbol} · Live price engine</b><span>tick <span id="tick">0</span>ms · simulated feed</span></div><div class="chart-wrap"><canvas id="mainChart"></canvas></div><div class="legend"><span><i style="background:#3b82f6"></i>Price</span><span>1m · 5m · 1h · 1D</span><span>Data source ready for broker adapter</span></div></div>
<div class="card"><div class="card-title"><b>Quant Signals</b><span>updated now</span></div>${ticker("NVDA","Momentum","BUY","91%")}${ticker("SPY","Regime","BUY","78%")}${ticker("QQQ","Mean reversion","WATCH","61%")}${ticker("AAPL","Factor score","BUY","74%")}${ticker("BTC-USD","Volatility","SELL","68%")}</div>
</div>
<div class="grid two" style="margin-top:13px"><div class="card"><div class="card-title"><b>Portfolio risk</b><span>real-time engine</span></div>${riskbar("Market beta",72)}${riskbar("Volatility",43)}${riskbar("Concentration",61)}${riskbar("Drawdown",27)}${riskbar("Liquidity",88)}</div>
<div class="card"><div class="card-title"><b>Decision assistant</b><span>beginner-friendly</span></div><div class="hero-signal"><span class="tag">CURRENT SETUP</span><div class="big positive">WAIT / SCALE IN</div><div class="sub">SPY · 78% confidence</div></div><div class="explain" style="margin-top:10px">Model sees positive regime + momentum, but volatility is elevated. Instead of “buy everything now”, the engine suggests staged sizing and a predefined invalidation level.</div></div></div>`}
function stat(a,b,c,d,pos){return `<div class="card"><div class="stat-label">${a}</div><div class="stat-value">${b}</div><div class="stat-foot ${pos===true?'positive':pos===false?'negative':''}">${c} · ${d}</div></div>`}
function ticker(a,b,c,d){return `<div class="ticker-row"><div class="ticker">${a}<small>${b}</small></div><div>${d}</div><div><span class="signal ${c.toLowerCase()}">${c}</span></div><div><div class="bar"><i style="width:${parseInt(d)}%"></i></div></div></div>`}
function riskbar(a,v){return `<div class="progress-row"><span>${a}</span><div class="bar"><i style="width:${v}%"></i></div><b>${v}</b></div>`}

function markets(){return `<div class="page-head"><div><div class="eyebrow">Market data</div><h1>Markets</h1><div class="sub">Watchlist, regime and live-style charting.</div></div><div class="actions"><button class="btn primary" onclick="toast('Feed adapter prepared — connect provider API in production.')">Connect data provider</button></div></div>
<div class="grid two"><div class="card chart-card"><div class="card-title"><b>SPY</b><span>NASDAQ/NYSE adapter-ready</span></div><div class="chart-wrap"><canvas id="marketChart"></canvas></div></div><div class="card"><div class="card-title"><b>Watchlist</b><span>5 assets</span></div>${state.watch.map((s,i)=>`<div class="ticker-row"><div class="ticker">${s}<small>${["Equity ETF","Tech ETF","Semiconductor","Mega cap","Crypto"][i]}</small></div><div class="${i===4?'negative':'positive'}">${i===4?'-1.21%':'+'+(1.2+i*.31).toFixed(2)+'%'}</div><div><span class="signal ${i===4?'sell':'buy'}">${i===4?'SELL':'BUY'}</span></div></div>`).join("")}</div></div>
<div class="grid three" style="margin-top:13px">${["Trend strength","Volatility","Market breadth"].map((x,i)=>`<div class="card"><div class="stat-label">${x}</div><div class="stat-value">${[74,38,66][i]}%</div><div class="stat-foot">${["Above 20/50/200 MA","Below 30D average","Positive advance/decline"][i]}</div></div>`).join("")}</div>`}

function quant(){return `<div class="page-head"><div><div class="eyebrow">Research engine</div><h1>Quant Lab</h1><div class="sub">Every model returns numbers plus an explanation of what they mean.</div></div></div>
<div class="grid module-grid">${modules.map((m,i)=>`<div class="card module" onclick="openModule(${i})"><div class="module-icon">${m[1]}</div><h3>${m[0]}</h3><p>${m[2]}</p><span class="open">Open module →</span></div>`).join("")}</div>`}

function strategies(){return `<div class="page-head"><div><div class="eyebrow">Strategy development</div><h1>Strategy Lab</h1><div class="sub">Describe a strategy in plain language or tune its parameters.</div></div><div class="actions"><button class="btn" onclick="toast('Strategy saved locally')">Save</button><button class="btn primary" onclick="go('backtest')">Backtest strategy</button></div></div>
<div class="grid two"><div class="card"><div class="card-title"><b>Strategy definition</b><span>plain English supported</span></div><div class="field"><label>Describe your strategy</label><textarea id="strategyText">Buy when 20-day momentum is positive and RSI is below 65. Reduce position when volatility rises above its 30-day median. Exit if drawdown exceeds 8%.</textarea></div><div class="input-grid" style="margin-top:10px"><div class="field"><label>Asset</label><input value="SPY" id="asset"/></div><div class="field"><label>Timeframe</label><select><option>1D</option><option>4H</option><option>1H</option></select></div><div class="field"><label>Initial capital</label><input value="100000" type="number"/></div></div><button class="btn primary" style="margin-top:12px" onclick="analyzeStrategy()">Analyze strategy</button></div>
<div class="card"><div class="card-title"><b>Strategy score</b><span>AI/quant checklist</span></div><div id="strategyResult" class="result"><div class="metric-grid">${metric("Robustness","8.1/10")}${metric("Complexity","Low")}${metric("Risk","Moderate")}${metric("Leakage","None detected")}</div><div class="explain" style="margin-top:14px">Before real money, the engine should run out-of-sample testing, walk-forward validation, transaction-cost assumptions and Monte Carlo stress tests.</div></div></div></div>`}
function metric(a,b){return `<div class="metric"><span>${a}</span><b>${b}</b></div>`}
function analyzeStrategy(){document.getElementById("strategyResult").innerHTML=`<div class="metric-grid">${metric("Robustness","8.4/10")}${metric("Expected CAGR","14.8%")}${metric("Max DD","-11.6%")}${metric("Sharpe","1.63")}</div><div class="explain" style="margin-top:14px"><b>Quant interpretation:</b> the idea has a coherent trend + risk overlay. The main danger is parameter overfitting. Next step: walk-forward + Monte Carlo + sensitivity analysis across nearby parameter values.</div>`;toast("Strategy analyzed")}
function backtest(){return `<div class="page-head"><div><div class="eyebrow">Historical simulation</div><h1>Backtesting</h1><div class="sub">Test a strategy before exposing capital to it.</div></div><button class="btn primary" onclick="runBacktest()">▶ Run backtest</button></div>
<div class="card"><div class="input-grid"><div class="field"><label>Strategy</label><select><option>Momentum + volatility filter</option><option>Mean reversion pairs</option><option>Custom strategy</option></select></div><div class="field"><label>Period</label><select><option>2018 — 2026</option><option>2022 — 2026</option><option>2025 — 2026</option></select></div><div class="field"><label>Fees + slippage</label><input value="0.08%" /></div></div></div>
<div id="backtestResult" style="margin-top:13px"><div class="grid metric-grid">${metric("CAGR","—")}${metric("Sharpe","—")}${metric("Max DD","—")}${metric("Win rate","—")}</div></div>`}
function runBacktest(){let r=seedPrices(180,100),eq=100000;for(let i=1;i<r.length;i++)eq*=Math.exp(0.0005+0.012*randn());let dd=-(8+Math.random()*8),sh=1.1+Math.random()*1;document.getElementById("backtestResult").innerHTML=`<div class="grid metric-grid">${metric("CAGR",(4+Math.random()*16).toFixed(1)+"%")}${metric("Sharpe",sh.toFixed(2))}${metric("Max DD",dd.toFixed(1)+"%")}${metric("Win rate",(52+Math.random()*14).toFixed(1)+"%")}</div><div class="card" style="margin-top:13px"><div class="explain"><b>Validation:</b> this is a demonstration backtest using generated data. Production mode must use licensed historical market data and account for corporate actions, survivorship bias, fees, spread and slippage.</div></div>`;toast("Backtest complete")}
function risk(){return `<div class="page-head"><div><div class="eyebrow">Risk management</div><h1>Risk Engine</h1><div class="sub">Position sizing and portfolio risk before execution.</div></div></div><div class="grid two"><div class="card"><div class="card-title"><b>Position sizing</b><span>Kelly + volatility target</span></div><div class="input-grid">${field("Win probability","55","win")}${field("Average win","4","aw")}${field("Average loss","2.5","al")}</div><button class="btn primary" style="margin-top:12px" onclick="calcKelly()">Calculate</button><div id="kelly" class="hero-signal" style="margin-top:13px"><span class="tag">KELLY</span><div class="big">—</div><div class="sub">Enter assumptions and calculate.</div></div></div><div class="card"><div class="card-title"><b>Portfolio limits</b></div>${riskbar("Single asset",22)}${riskbar("Sector concentration",39)}${riskbar("Liquidity risk",17)}${riskbar("Tail risk",34)}<div class="explain">Risk engine should be allowed to block an order when predefined portfolio limits are violated.</div></div></div>`}
function field(label,val,id){return `<div class="field"><label>${label}</label><input id="${id}" value="${val}" type="number"/></div>`}
function calcKelly(){let p=+win.value/100,w=+aw.value/100,l=+al.value/100,b=w/l,k=(p*b-(1-p))/b;let half=Math.max(0,k/2);document.getElementById("kelly").innerHTML=`<span class="tag">HALF KELLY</span><div class="big positive">${(half*100).toFixed(2)}%</div><div class="sub">Full Kelly: ${(k*100).toFixed(2)}% · recommended cap depends on portfolio risk.</div>`}

function portfolio(){return `<div class="page-head"><div><div class="eyebrow">Capital allocation</div><h1>Portfolio</h1><div class="sub">Exposure, P&L and diversification.</div></div><button class="btn primary" onclick="toast('Rebalancing proposal generated')">Generate rebalance</button></div><div class="grid stats">${stat("Net liquidation","$124,860","+2.84%","30D",1)}${stat("Cash","$21,420","17.2%","of portfolio",1)}${stat("Beta","0.91","-0.08","vs market",1)}${stat("Volatility","12.8%","+1.1%","30D",false)}${stat("CVaR 95%","-$4,820","3.86%","of NAV",false)}</div><div class="card"><div class="card-title"><b>Holdings</b><span>demo portfolio</span></div><table class="table"><thead><tr><th>Asset</th><th>Weight</th><th>P&L</th><th>Risk contribution</th><th>Signal</th></tr></thead><tbody>${[["SPY","32%","+4.2%","28%","BUY"],["QQQ","21%","+7.8%","25%","BUY"],["NVDA","14%","+18.1%","21%","WATCH"],["AAPL","9%","+3.4%","8%","BUY"],["BTC-USD","7%","-2.1%","12%","REDUCE"]].map(r=>`<tr><td><b>${r[0]}</b></td><td>${r[1]}</td><td class="positive">${r[2]}</td><td>${r[3]}</td><td><span class="signal ${r[4]==="REDUCE"?"sell":r[4]==="WATCH"?"watch":"buy"}">${r[4]}</span></td></tr>`).join("")}</tbody></table></div>`}

function alerts(){return `<div class="page-head"><div><div class="eyebrow">Decision layer</div><h1>Signals & Alerts</h1><div class="sub">The system watches your conditions instead of forcing you to stare at charts.</div></div><button class="btn primary" onclick="toast('Alert created')">＋ Create alert</button></div><div class="grid three">${["SPY breaks above 20D high","NVDA momentum regime change","QQQ pairs z-score > 2"].map((x,i)=>`<div class="card"><span class="tag">${["TRIGGERED","MONITORING","MONITORING"][i]}</span><h3 style="font-size:13px">${x}</h3><p class="sub">${["2 minutes ago","Live","Live"][i]}</p><button class="btn" onclick="toast('Alert settings opened')">Configure</button></div>`).join("")}</div>`}
function learn(){return `<div class="page-head"><div><div class="eyebrow">Beginner mode</div><h1>Learn & Decide</h1><div class="sub">No quant background required.</div></div></div><div class="grid two"><div class="card"><h3>What should I do?</h3><div class="explain">QuantForge should never hide uncertainty. Every signal gets a confidence score, the key reasons, invalidation conditions and the risk of being wrong.</div><div style="margin-top:14px">${["What is a stock?","What is volatility?","Why does diversification matter?","What is a drawdown?","How does a backtest work?","What does Sharpe ratio mean?"].map(x=>`<div class="ticker-row"><div>${x}</div><button class="btn" onclick="toast('Lesson: ${x}')">Learn</button></div>`).join("")}</div></div><div class="card"><h3>Current recommendation</h3><div class="hero-signal"><span class="tag">EDUCATIONAL VIEW</span><div class="big">DON'T RUSH</div><div class="sub">Understand risk before execution.</div></div><p class="result">A beginner should first understand position size, diversification, fees, drawdown and the difference between a historical backtest and a future prediction.</p></div></div>`}

function openModule(i){let m=modules[i];if(i===1){go("risk");return}let extra=i===0?`<div class="grid two"><div class="card"><div class="input-grid">${field("Asset A","SPY","a")}${field("Asset B","QQQ","b")}${field("Lookback","120","lb")}</div><button class="btn primary" style="margin-top:12px" onclick="pairs()">Run pair analysis</button><div id="pairs" style="margin-top:12px"></div></div><div class="card"><div class="card-title"><b>How to read it</b></div><div class="explain">A useful pair tends to have a stable relationship. Z-score tells you how unusual the current spread is. Cointegration is stronger evidence than simple correlation.</div></div></div>`:
i===2?`<div class="card"><div class="input-grid">${field("Spot","100","spot")}${field("Strike","105","strike")}${field("Volatility %","28","vol")}${field("Rate %","4.2","rate")}${field("Days","45","days")}</div><button class="btn primary" style="margin-top:12px" onclick="bs()">Calculate option</button><div id="bs" class="grid metric-grid" style="margin-top:13px"></div></div>`:
i===3?`<div class="card"><div class="input-grid">${field("Starting capital","100000","mcCap")}${field("Expected return %","12","mcRet")}${field("Annual vol %","18","mcVol")}${field("Years","3","mcYears")}</div><button class="btn primary" style="margin-top:12px" onclick="mc()">Run 10,000 scenarios</button><div id="mc" style="margin-top:13px"></div></div>`:
`<div class="grid two"><div class="card"><div class="explain"><b>${m[0]}</b><br/>This module is connected to the same strategy/risk layer. In production it will consume real market data, store model versions and show confidence intervals rather than a single “magic” prediction.</div><button class="btn primary" style="margin-top:12px" onclick="toast('${m[0]} scan started')">Run analysis</button></div><div class="card"><div class="card-title"><b>Model output</b><span>demo</span></div>${riskbar("Signal confidence",74)}${riskbar("Data quality",91)}${riskbar("Model stability",82)}${riskbar("Opportunity",67)}</div></div>`;
document.getElementById("view").innerHTML=`<div class="page-head"><div><div class="eyebrow">Quant module</div><h1>${m[0]}</h1><div class="sub">${m[2]}</div></div><button class="btn" onclick="go('quant')">← All modules</button></div>${extra}`}
}
function pairs(){let z=(Math.random()*4-2).toFixed(2),corr=(.72+Math.random()*.25).toFixed(2);document.getElementById("pairs").innerHTML=`<div class="grid metric-grid">${metric("Correlation",corr)}${metric("Z-score",z)}${metric("Half-life",(3+Math.random()*12).toFixed(1)+"d")}${metric("Status",Math.abs(z)>1.8?"SETUP":"NO EDGE")}</div><div class="explain" style="margin-top:12px">${Math.abs(z)>1.8?"Spread is unusually far from its mean. This is a candidate for deeper cointegration + execution-cost testing, not an automatic trade.":"Current spread is close to its mean; wait for a stronger deviation."}</div>`}
function bs(){let S=+spot.value,K=+strike.value,v=+vol.value/100,r=+rate.value/100,T=+days.value/365;let d1=(Math.log(S/K)+(r+.5*v*v)*T)/(v*Math.sqrt(T)),d2=d1-v*Math.sqrt(T),N=x=>.5*(1+erf(x/Math.sqrt(2))),call=S*N(d1)-K*Math.exp(-r*T)*N(d2),delta=N(d1),gamma=Math.exp(-d1*d1/2)/(S*v*Math.sqrt(2*Math.PI*T));document.getElementById("bs").innerHTML=metric("Call value","$"+call.toFixed(2))+metric("Delta",delta.toFixed(3))+metric("Gamma",gamma.toFixed(4))+metric("d1/d2",d1.toFixed(2)+" / "+d2.toFixed(2))}
function erf(x){let s=x<0?-1:1;x=Math.abs(x);let a=1/(1+.3275911*x),y=1-((((((1.061405429*a-.356563782)*a)+1.781477937)*a)-.82215223)*a+.254829592)*a*Math.exp(-x*x);return s*y}
function mc(){let cap=+mcCap.value,mu=+mcRet.value/100,sig=+mcVol.value/100,years=+mcYears.value,n=10000,vals=[];for(let j=0;j<n;j++){let p=cap;for(let y=0;y<years;y++)p*=Math.exp((mu-.5*sig*sig)+sig*randn());vals.push(p)}vals.sort((a,b)=>a-b);let q5=vals[Math.floor(n*.05)],med=vals[Math.floor(n*.5)],q95=vals[Math.floor(n*.95)];document.getElementById("mc").innerHTML=`<div class="grid metric-grid">${metric("5th percentile","$"+Math.round(q5).toLocaleString())}${metric("Median","$"+Math.round(med).toLocaleString())}${metric("95th percentile","$"+Math.round(q95).toLocaleString())}${metric("P(profit)",(vals.filter(x=>x>cap).length/n*100).toFixed(1)+"%")}</div><div class="explain" style="margin-top:12px">Monte Carlo does not predict the future. It answers: “If these assumptions were approximately true, how wide could the range of outcomes be?”</div>`}

function render(){nav();let html={dashboard:dashboard,markets:markets,quant:quant,strategies:strategies,backtest:backtest,risk:risk,portfolio:portfolio,alerts:alerts,learn:learn}[state.view]||dashboard;document.getElementById("view").innerHTML=html();setTimeout(()=>{if(state.view==="dashboard")drawChart("mainChart",state.prices);if(state.view==="markets")drawChart("marketChart",state.prices)},30)}
document.getElementById("themeBtn").onclick=()=>toast("Dark navy theme is the active terminal theme");
document.getElementById("globalSearch").onkeydown=e=>{if(e.key==="Enter"){let q=e.target.value.toLowerCase();if(q.includes("kelly")||q.includes("black")||q.includes("monte")||q.includes("quant"))go("quant");else toast("Search ready for the connected research index")}};
livePrices();render();
setInterval(()=>{livePrices();if(state.view==="dashboard"){drawChart("mainChart",state.prices);let t=document.getElementById("tick");if(t)t.textContent=Date.now()%1000}if(state.view==="markets")drawChart("marketChart",state.prices)},1200);
window.addEventListener("resize",()=>{if(state.view==="dashboard")drawChart("mainChart",state.prices);if(state.view==="markets")drawChart("marketChart",state.prices)});
